name: Deploy to GoDaddy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main  # Triggers the workflow on push events to the main branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'  # Set to the Node.js version used in your project

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build  # Runs your project's build command
      